# Electrical Distribution Network Energy Consumption Forecasting based upon Victorian MRIM Meter Data

## Background
Forecasting energy demand plays a vital role in operation and planning of modern power systems. 

**Oversupply:**<br>
When the supply exceeds the demand, the energy can be stored. However, they can't be stored in a large capacity. In addition, when the energy is stored, it is expensive, requires high maintenance and has a limited lifespan.

**Undersupply:**<br>
When the supply doesn't meet the demand, the supply line could be overloaded and potentially lead to blackouts.

## Objective
Providing reliable forecasting of energy consumption results in a better management of the electrical distribution network. The objective of this Project is therefore to forecast energy consumption for an electrical distribution network based on Victorian MRIM meter data. The forecast will be built upon machine learning models that is utilised in time series problems. In addition, the energy consumption will be forecasted based purely from historical data.
<br>
<br>
The energy consumption will be forecasted based on historical data that are obtained directly via MRIM meters from an electrical distribution network. The rationale behind this is to alleviate the dependence of other parameters, such as the weather, which are in itself also forecasts.  If the weather or such similar parameters are forecasted incorrectly, it will directly impact the accuracy of the energy consumption forecast.

# Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

%matplotlib inline

## Data Source

The data was acquired from AEMO (Australing Market Energy Operator) website: <br><br>
https://aemo.com.au/energy-systems/electricity/national-electricity-market-nem/data-nem/metering-data/victorian-mrim-meter-data<br><br>
The following files contain the aggregated half hour energy for all type 5 meter installation sites (meter installation code = MRIM) for each of the profile areas relating to the 5 distribution networks in Victoria.

# 2019

In [2]:
file_Jul_Sept = '../data/VIC_201907 to 201909.csv'
file_Apr_Jun = '../data/VIC_20190401_20190630.csv'
file_Jan_Mar = '../data/VIC_20190101_20190331.csv'

data1 = pd.read_csv(file_Jul_Sept)
data2 = pd.read_csv(file_Apr_Jun)
data3 = pd.read_csv(file_Jan_Mar)

data2019 = pd.concat([data3,data2,data1])

# 2018

In [3]:
file2018_Oct_Dec = '../data/VIC_20181001_20181231.csv'
file2018_Jul_Sept = '../data/VIC_20180701_20180930.csv'
file2018_Apr_Jun = '../data/VIC_20180401_20180630.csv'
file2018_Jan_Mar = '../data/VIC_20180101_20180331.csv'

data4 = pd.read_csv(file2018_Jan_Mar)
data5 = pd.read_csv(file2018_Apr_Jun)
data6 = pd.read_csv(file2018_Jul_Sept)
data7 = pd.read_csv(file2018_Oct_Dec)

data2018 = pd.concat([data4,data5,data6,data7])

# 2017

In [4]:
file2017_Oct_Dec = '../data/VIC_20171001_20171231.csv'
file2017_Jul_Sept = '../data/VIC_20170701_20170930.csv'
file2017_Apr_Jun = '../data/VIC_20170401_20170630.csv'
file2017_Jan_Mar = '../data/VIC_20170101_20170331.csv'

data8 = pd.read_csv(file2017_Jan_Mar)
data9 = pd.read_csv(file2017_Apr_Jun)
data10 = pd.read_csv(file2017_Jul_Sept)
data11 = pd.read_csv(file2017_Oct_Dec)

data2017 = pd.concat([data8,data9,data10,data11])

# 2016

In [5]:
file2016_Jan_Mar = '../data/VIC_20160101_20160331.csv'
file2016_Apr_Jun = '../data/VIC_20160401_20160630.csv'
file2016_Jul_Sept = '../data/VIC_20160701_20160930.csv'
file2016_Oct_Dec = '../data/VIC_20161001_20161231.csv'

data_2016_Jan_Mar = pd.read_csv(file2016_Jan_Mar)
data_2016_Apr_Jun = pd.read_csv(file2016_Apr_Jun)
data_2016_Jul_Sept = pd.read_csv(file2016_Jul_Sept)
data_2016_Oct_Dec = pd.read_csv(file2016_Oct_Dec)

data2016 = pd.concat([data_2016_Jan_Mar, data_2016_Apr_Jun, data_2016_Jul_Sept, data_2016_Oct_Dec])

# 2015

In [6]:
file2015_Jan_Mar = '../data/VIC_20150101_20150331.csv'
file2015_Apr_Jun = '../data/VIC_20150401_20150630.csv'
file2015_Jul_Sept = '../data/VIC_20150701_20150930.csv'
file2015_Oct_Dec = '../data/VIC_20151001_20151231.csv'

data_2015_Jan_Mar = pd.read_csv(file2015_Jan_Mar)
data_2015_Apr_Jun = pd.read_csv(file2015_Apr_Jun)
data_2015_Jul_Sept = pd.read_csv(file2015_Jul_Sept)
data_2015_Oct_Dec = pd.read_csv(file2015_Oct_Dec)

data2015 = pd.concat([data_2015_Jan_Mar, data_2015_Apr_Jun, data_2015_Jul_Sept, data_2015_Oct_Dec])

# 2014

In [7]:
#file2011_2014_Mar = '../data/Vic_mrim_sum_web.csv'
file2014_Apr_Jun = '../data/VIC_20140401_20140630.csv'
file2014_Jul_Sept = '../data/VIC_20140701_20140930.csv'
file2014_Oct_Dec = '../data/VIC_20141001_20141231.csv'

#data_2011_2014_Mar = pd.read_csv(file2011_2014_Mar)
data_2014_Apr_Jun = pd.read_csv(file2014_Apr_Jun)
data_2014_Jul_Sept = pd.read_csv(file2014_Jul_Sept)
data_2014_Oct_Dec = pd.read_csv(file2014_Oct_Dec)

#data_2011_2014 = pd.concat([data_2011_2014_Mar, data_2014_Apr_Jun, data_2014_Jul_Sept, data_2014_Oct_Dec])
data2014 = pd.concat([data_2014_Apr_Jun, data_2014_Jul_Sept, data_2014_Oct_Dec])

# Concatenate the whole data

In [8]:
#data2011_2019 = pd.concat([data_2011_2014, 
#                  data2015, 
#                  data2016, 
#                  data2017, 
#                  data2018,
#                  data2019])
data_2014_2019 = pd.concat([data2014, 
                  data2015, 
                  data2016, 
                  data2017, 
                  data2018,
                  data2019])

In [9]:
data_2014_2019

,SETTD,PROFILEAREA,DAILYT,VAL01,VAL02,VAL03,VAL04,VAL05,VAL06,VAL07,...,VAL40,VAL41,VAL42,VAL43,VAL44,VAL45,VAL46,VAL47,VAL48,DCTC
0,01/04/2014,CITIPOWER,6363749.701,83948.634,75686.720,70851.453,67607.385,66124.942,64953.942,64306.671,...,160069.821,152968.056,145198.285,133952.389,121154.389,113845.677,111219.265,111446.631,106211.512,MRIM
1,02/04/2014,CITIPOWER,5630825.535,93503.589,84693.357,79590.499,76384.550,74882.906,73439.136,72621.772,...,124538.811,119661.538,113667.967,105081.148,95684.746,91694.112,91698.657,93790.379,89377.501,MRIM
2,03/04/2014,CITIPOWER,5173891.385,77688.455,69851.785,65002.304,62203.224,60863.263,59985.433,59409.226,...,122934.586,118084.353,112122.808,104010.749,94635.246,90432.761,90406.507,92838.823,89320.024,MRIM
3,04/04/2014,CITIPOWER,5044050.180,77761.113,69530.046,64437.280,61304.327,59653.842,58588.591,58218.212,...,114460.060,110398.858,105854.672,100063.838,93741.476,91659.930,93286.271,96403.437,92482.282,MRIM
4,05/04/2014,CITIPOWER,4383318.300,80930.298,72390.242,66461.934,63121.603,60993.088,59567.853,58667.439,...,107937.349,104206.712,100866.709,96744.697,91474.783,91223.017,94194.091,98842.620,95486.413,MRIM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
455,26/09/2019,VICAGL,4001114.451,93454.970,84713.011,77795.025,73292.108,69989.268,67741.988,66472.110,...,119039.081,117595.047,115867.546,112913.320,109125.450,103408.389,96723.787,103420.008,96419.602,MRIM
456,27/09/2019,VICAGL,4647865.392,86926.437,78953.171,72648.284,68093.437,64821.229,62449.575,61134.570,...,146764.156,144014.526,140678.398,135886.240,130066.807,122198.889,113552.702,118929.233,110941.401,MRIM
457,28/09/2019,VICAGL,4414391.115,100309.453,90927.427,83737.079,78066.774,73824.441,71165.113,69179.534,...,135110.328,133010.920,130779.206,127109.849,122441.172,115717.996,107654.538,113909.051,106123.665,MRIM
458,29/09/2019,VICAGL,4523173.698,96313.432,87879.723,80847.354,75603.400,71900.217,68917.269,66937.290,...,149957.139,146834.934,142413.107,135813.492,127117.029,116306.428,105403.388,109711.921,101669.008,MRIM
459,30/09/2019,VICAGL,4916430.836,91469.323,83353.504,77014.741,72019.190,68530.865,66064.381,64582.383,...,162293.280,158755.270,154763.447,147777.348,137761.772,125253.789,112555.101,115577.986,106455.626,MRIM

In [10]:
data_2014_2019.columns

Index(['SETTD', 'PROFILEAREA', 'DAILYT', 'VAL01', 'VAL02', 'VAL03', 'VAL04',
       'VAL05', 'VAL06', 'VAL07', 'VAL08', 'VAL09', 'VAL10', 'VAL11', 'VAL12',
       'VAL13', 'VAL14', 'VAL15', 'VAL16', 'VAL17', 'VAL18', 'VAL19', 'VAL20',
       'VAL21', 'VAL22', 'VAL23', 'VAL24', 'VAL25', 'VAL26', 'VAL27', 'VAL28',
       'VAL29', 'VAL30', 'VAL31', 'VAL32', 'VAL33', 'VAL34', 'VAL35', 'VAL36',
       'VAL37', 'VAL38', 'VAL39', 'VAL40', 'VAL41', 'VAL42', 'VAL43', 'VAL44',
       'VAL45', 'VAL46', 'VAL47', 'VAL48', 'DCTC'],
      dtype='object')

In [11]:
data_2014_2019.PROFILEAREA.unique()

array(['CITIPOWER', 'POWERCOR', 'TXU', 'UNITED', 'VICAGL'], dtype=object)

**The data contained energy consumption in (kWh) which are distributed from 5 different electrical distribution networks. Each distribution network is responsible for distributing electrical energy for different parts of Victoria and hence, the behaviour of the data will most likely be different for each network. Hence,  different machine learning model may perform better for each respective electrical distribution network. For this Project, the exercise will be focussed on setting an approach using the Python programming language and determining the models that will be most appropriate for forecasting the energy consumption based on Victorian MRIM meters that were installed by CitiPower.**

In [12]:
def sep_providers(df, column):
    output = []
    providers = df[column].unique()
    for provider in providers:
        output.append(df[df[column] == provider])
    return output

In [13]:
check = sep_providers(data_2014_2019, 'PROFILEAREA')

In [14]:
data = check[0]

In [15]:
data.head()

,SETTD,PROFILEAREA,DAILYT,VAL01,VAL02,VAL03,VAL04,VAL05,VAL06,VAL07,...,VAL40,VAL41,VAL42,VAL43,VAL44,VAL45,VAL46,VAL47,VAL48,DCTC
0,01/04/2014,CITIPOWER,6363749.701,83948.634,75686.720,70851.453,67607.385,66124.942,64953.942,64306.671,...,160069.821,152968.056,145198.285,133952.389,121154.389,113845.677,111219.265,111446.631,106211.512,MRIM
1,02/04/2014,CITIPOWER,5630825.535,93503.589,84693.357,79590.499,76384.550,74882.906,73439.136,72621.772,...,124538.811,119661.538,113667.967,105081.148,95684.746,91694.112,91698.657,93790.379,89377.501,MRIM
2,03/04/2014,CITIPOWER,5173891.385,77688.455,69851.785,65002.304,62203.224,60863.263,59985.433,59409.226,...,122934.586,118084.353,112122.808,104010.749,94635.246,90432.761,90406.507,92838.823,89320.024,MRIM
3,04/04/2014,CITIPOWER,5044050.180,77761.113,69530.046,64437.280,61304.327,59653.842,58588.591,58218.212,...,114460.060,110398.858,105854.672,100063.838,93741.476,91659.930,93286.271,96403.437,92482.282,MRIM
4,05/04/2014,CITIPOWER,4383318.300,80930.298,72390.242,66461.934,63121.603,60993.088,59567.853,58667.439,...,107937.349,104206.712,100866.709,96744.697,91474.783,91223.017,94194.091,98842.620,95486.413,MRIM

### For Presentation Slides

In [16]:
pd.options.display.max_rows

60

In [17]:
pd.options.display.max_columns

20

In [18]:
pd.set_option("display.max_columns", 13)

In [19]:
data.head()

,SETTD,PROFILEAREA,DAILYT,VAL01,VAL02,VAL03,...,VAL44,VAL45,VAL46,VAL47,VAL48,DCTC
0,01/04/2014,CITIPOWER,6363749.701,83948.634,75686.720,70851.453,...,121154.389,113845.677,111219.265,111446.631,106211.512,MRIM
1,02/04/2014,CITIPOWER,5630825.535,93503.589,84693.357,79590.499,...,95684.746,91694.112,91698.657,93790.379,89377.501,MRIM
2,03/04/2014,CITIPOWER,5173891.385,77688.455,69851.785,65002.304,...,94635.246,90432.761,90406.507,92838.823,89320.024,MRIM
3,04/04/2014,CITIPOWER,5044050.180,77761.113,69530.046,64437.280,...,93741.476,91659.930,93286.271,96403.437,92482.282,MRIM
4,05/04/2014,CITIPOWER,4383318.300,80930.298,72390.242,66461.934,...,91474.783,91223.017,94194.091,98842.620,95486.413,MRIM

In [20]:
data.tail()

,SETTD,PROFILEAREA,DAILYT,VAL01,VAL02,VAL03,...,VAL44,VAL45,VAL46,VAL47,VAL48,DCTC
335,26/09/2019,CITIPOWER,5357014.025,104634.319,94261.824,85886.697,...,119627.636,117257.730,116889.511,116537.564,111083.906,MRIM
336,27/09/2019,CITIPOWER,5219544.620,99948.011,90329.481,82614.079,...,132064.546,128539.473,127118.810,126562.299,120734.248,MRIM
337,28/09/2019,CITIPOWER,5036389.054,109579.556,99327.006,90975.407,...,125324.594,122525.891,121376.335,121272.505,115959.738,MRIM
338,29/09/2019,CITIPOWER,4993439.774,105339.777,95979.319,88359.469,...,130184.465,123603.663,119416.449,117391.576,111069.642,MRIM
339,30/09/2019,CITIPOWER,6030581.529,100149.694,90839.884,83260.137,...,146284.126,136462.910,129778.602,125565.504,118117.204,MRIM

In [21]:
data.shape

(2009, 52)

In [22]:
# reset options for the pandas display
pd.reset_option('all')

: boolean
    use_inf_as_null had been deprecated and will be removed in a future
    version. Use `use_inf_as_na` instead.

In [23]:
data.to_csv('data_citipower.csv')